### ISSUE TITLE
hidden_unit

### ISSUE THREAD

**Issue by uliuycy** [Lysarthas/Time-Transformer#1]
TypeError: discriminator() missing 1 required positional argument: 'hidden_unit'.How much should hidden unit be set to

**Comment by Lysarthas** [comment]
Hi, can you provide more details regarding this error?

**Comment by uliuycy** [comment]
In aee-trainer.py, there is a hidden unit variable in networks. discriminator (input_shape=late, hidden unit=32) that has not been assigned a value. The assignment I saw in my paper was 32

**Comment by uliuycy** [comment]
Are there any verification operations to determine the effectiveness of model generation

**Comment by Lysarthas** [comment]
> In aee-trainer.py, there is a hidden unit variable in networks. discriminator (input_shape=late, hidden unit=32) that has not been assigned a value. The assignment I saw in my paper was 32

Ah, yes, that's was a mistake, the hidden unit is assigended 32.

**Comment by Lysarthas** [comment]
> Are there any verification operations to determine the effectiveness of model generation

Do you mean during test time? we provide details in the tutorial notebook, where we have t-SNE plot of distribution, distriminative and predictive score. And the FID score is calculated in ts2vec.ipynb please follow the instructions in README.

**Comment by uliuycy** [comment]
Thank you very much for your reply. Is that it, tutorial. ipynb
